import 'dart:convert';
import 'package:http/http.dart' as http;

import 'Auto.dart';

class Api {
  static Future<Autogenerated> getRandomQuote() async {
    try {
      final response = await http.get(
          Uri.parse('https://opentdb.com/api.php?amount=100&category=9&difficulty=medium&type=multiple'));

      if (response.statusCode == 200) {
        return Autogenerated.fromJson(jsonDecode(response.body));
      } else {
        print('API Error: ${response.statusCode}');
        throw Exception('Failed to load quote');
      }
    } catch (e) {
      print('Error: $e');
      throw Exception('Failed to generate quote');
    }
  }
}