class Autogenerated {
  int responseCode;
  List<Results> results;

  Autogenerated({required this.responseCode, required this.results});

  Autogenerated.fromJson(Map<String, dynamic> json)
      : responseCode = json['response_code'],
        results = (json['results'] as List<dynamic>?)
            ?.map((e) => Results.fromJson(e as Map<String, dynamic>))
            .toList() ??
            [];

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['response_code'] = responseCode;
    data['results'] = results.map((e) => e.toJson()).toList();
    return data;
  }
}

class Results {
  String? type;
  String? difficulty;
  String? category;
  String? question;
  String? correctAnswer;
  List<String>? incorrectAnswers;

  Results({
    this.type,
    this.difficulty,
    this.category,
    this.question,
    this.correctAnswer,
    this.incorrectAnswers,
  });

  Results.fromJson(Map<String, dynamic> json)
      : type = json['type'],
        difficulty = json['difficulty'],
        category = json['category'],
        question = json['question'],
        correctAnswer = json['correct_answer'],
        incorrectAnswers = (json['incorrect_answers'] as List<dynamic>?)
            ?.cast<String>() ??
            [];

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['type'] = type;
    data['difficulty'] = difficulty;
    data['category'] = category;
    data['question'] = question;
    data['correct_answer'] = correctAnswer;
    data['incorrect_answers'] = incorrectAnswers;
    return data;
  }
}
